# Generated by Django 3.1.7 on 2021-08-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.JSONField(default={})),
                ('phone', models.CharField(max_length=50)),
                ('website', models.JSONField(default={})),
                ('company', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placeholderapi.bloguser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placeholderapi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placeholderapi.bloguser')),
            ],
        ),
    ]
