# Generated by Django 3.1.7 on 2021-08-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeholderapi', '0003_auto_20210802_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
